package repomgr

import (
	"bytes"
	"fmt"
	"log/slog"
	"os"
	"path/filepath"
)

type DoorstopVersion int

const (
	DoorstopVersionUnknown DoorstopVersion = iota
	DoorstopVersion3
	DoorstopVersion4
)

func (v DoorstopVersion) String() string {
	switch v {
	case DoorstopVersion3:
		return "Doorstop v3"
	case DoorstopVersion4:
		return "Doorstop v4"
	default:
		return "Doorstop Unknown"
	}
}

// DetectDoorstopVersion inspects winhttp.dll in the given directory to determine if it is Doorstop 3 or Doorstop 4.
func DetectDoorstopVersion(dllDir string) DoorstopVersion {
	dllPath := filepath.Join(dllDir, "winhttp.dll")
	data, err := os.ReadFile(dllPath)
	if err != nil {
		slog.Debug("winhttp.dll not found in dllDir, cannot detect doorstop version", "path", dllPath, "error", err)
		return DoorstopVersionUnknown
	}

	// Signatures in UTF-16
	// Doorstop 3 has "--doorstop-enable"
	// Doorstop 4 has "--doorstop-enabled"
	v3SigUTF16 := []byte{'-', 0, '-', 0, 'd', 0, 'o', 0, 'o', 0, 'r', 0, 's', 0, 't', 0, 'o', 0, 'p', 0, '-', 0, 'e', 0, 'n', 0, 'a', 0, 'b', 0, 'l', 0, 'e', 0, 0, 0}
	v4SigUTF16 := []byte{'-', 0, '-', 0, 'd', 0, 'o', 0, 'o', 0, 'r', 0, 's', 0, 't', 0, 'o', 0, 'p', 0, '-', 0, 'e', 0, 'n', 0, 'a', 0, 'b', 0, 'l', 0, 'e', 0, 'd', 0}

	if bytes.Contains(data, v3SigUTF16) {
		return DoorstopVersion3
	}
	if bytes.Contains(data, v4SigUTF16) {
		return DoorstopVersion4
	}

	// Fallback to ASCII search
	if bytes.Contains(data, []byte("--doorstop-enabled")) {
		return DoorstopVersion4
	}
	if bytes.Contains(data, []byte("--doorstop-enable")) {
		return DoorstopVersion3
	}

	return DoorstopVersionUnknown
}

// DetectBepInExTarget locates the target preloader/entrypoint assembly inside BepInEx/core.
func DetectBepInExTarget(dllDir string) (targetAssembly string, isIL2CPP bool) {
	il2cppCandidate := filepath.Join(dllDir, "BepInEx", "core", "BepInEx.Unity.IL2CPP.dll")
	if _, err := os.Stat(il2cppCandidate); err == nil {
		return il2cppCandidate, true
	}

	mono6Candidate := filepath.Join(dllDir, "BepInEx", "core", "BepInEx.Unity.Mono.dll")
	if _, err := os.Stat(mono6Candidate); err == nil {
		return mono6Candidate, false
	}

	// BepInEx 5.x Mono default
	preloaderCandidate := filepath.Join(dllDir, "BepInEx", "core", "BepInEx.Preloader.dll")
	return preloaderCandidate, false
}

// BuildDoorstopArgs constructs the CLI arguments for the game executable based on the detected Doorstop and BepInEx versions.
func BuildDoorstopArgs(dllDir string) ([]string, error) {
	if dllDir == "" {
		return nil, nil
	}

	ver := DetectDoorstopVersion(dllDir)
	targetAssembly, isIL2CPP := DetectBepInExTarget(dllDir)

	slog.Info("Detected Doorstop configuration", "version", ver.String(), "targetAssembly", targetAssembly, "isIL2CPP", isIL2CPP)

	var args []string

	switch ver {
	case DoorstopVersion3:
		// Doorstop 3.x syntax: --doorstop-enable true --doorstop-target <path>
		args = append(args,
			"--doorstop-enable", "true",
			"--doorstop-target", targetAssembly,
		)
	case DoorstopVersion4:
		// Doorstop 4.x syntax: --doorstop-enabled true --doorstop-target-assembly <path>
		args = append(args,
			"--doorstop-enabled", "true",
			"--doorstop-target-assembly", targetAssembly,
		)
		if isIL2CPP {
			coreClrPath := filepath.Join(dllDir, "dotnet", "coreclr.dll")
			corlibDir := filepath.Join(dllDir, "dotnet")
			args = append(args,
				"--doorstop-clr-corlib-dir", corlibDir,
				"--doorstop-clr-runtime-coreclr-path", coreClrPath,
			)
		}
	default:
		// Unknown version: pass both Doorstop 3 and Doorstop 4 arguments for maximum compatibility
		args = append(args,
			"--doorstop-enable", "true",
			"--doorstop-target", targetAssembly,
			"--doorstop-enabled", "true",
			"--doorstop-target-assembly", targetAssembly,
		)
		if isIL2CPP {
			coreClrPath := filepath.Join(dllDir, "dotnet", "coreclr.dll")
			corlibDir := filepath.Join(dllDir, "dotnet")
			args = append(args,
				"--doorstop-clr-corlib-dir", corlibDir,
				"--doorstop-clr-runtime-coreclr-path", coreClrPath,
			)
		}
	}

	return args, nil
}

// GenerateDoorstopConfig generates a doorstop_config.ini string suitable for the detected Doorstop and BepInEx versions.
// Both [UnityDoorstop] (Doorstop 3) and [General] (Doorstop 4) sections are included so that the file works seamlessly with either version.
func GenerateDoorstopConfig(basePath string) string {
	targetAssembly, isIL2CPP := DetectBepInExTarget(basePath)
	coreClrPath := filepath.Join(basePath, "dotnet", "coreclr.dll")
	corlibDir := filepath.Join(basePath, "dotnet")

	var il2cppSection string
	if isIL2CPP {
		il2cppSection = fmt.Sprintf(`
[Il2Cpp]
coreclr_path = %s
corlib_dir = %s
`, coreClrPath, corlibDir)
	}

	return fmt.Sprintf(`# Generated by MODREPO
# Doorstop 3.x configuration (BepInEx 5.x / Mono)
[UnityDoorstop]
enabled = true
targetAssembly = %s
redirectOutputLog = false
ignoreDisableSwitch = false
dllSearchPathOverride =

[MonoBackend]
runtimeLib =
configDir =
corlibDir =
debugEnabled = false
debugSuspend = false
debugAddress = 127.0.0.1:10000

# Doorstop 4.x configuration (BepInEx 6.x / IL2CPP / Mono)
[General]
enabled = true
target_assembly = %s
redirect_output_log = false
boot_config_override =
ignore_disable_switch = false

[UnityMono]
dll_search_path_override =
debug_enabled = false
debug_start_server = true
debug_address = 127.0.0.1:10000
debug_suspend = false
%s`, targetAssembly, targetAssembly, il2cppSection)
}
