name: ci
run-name: ci on ${{ github.ref_name }}

on:
  push:
    branches:
      - master
    paths:
      - "**.go"
      - "**/go.sum"
      - "**/go.mod"
      - ".golangci.yml"
  pull_request:
    branches:
      - master
    paths:
      - "**.go"
      - "**/go.sum"
      - "**/go.mod"
      - ".golangci.yml"

permissions:
  contents: read

jobs:
  golangci:
    name: lint
    runs-on: windows-latest
    steps:
      - name: Configure Git
        run: |
          git config --global core.autocrlf false
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
      - name: Cache golangci-lint cache
        id: cache-golangci-lint
        env:
          cache-name: cache-golangci-lint
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: ~/.cache/golangci-lint
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('.golangci.yml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: "go.mod"
      - name: go generate
        run: go generate ./...
      - name: golangci-lint
        uses: golangci/golangci-lint-action@ba0d7d2ec06a0ea1cb5fa41b2e4a3ab91d21278a # v9.3.0

  test:
    name: test
    runs-on: windows-latest
    steps:
      - name: Configure Git
        run: |
          git config --global core.autocrlf false
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
      - name: Cache Go modules
        id: cache-go-mod
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        env:
          cache-name: cache-go-mod
        with:
          path: |
            ~\AppData\Local\go-build
            ~\go\pkg\mod
          key: ${{ runner.os }}-go-${{ env.cache-name }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-${{ env.cache-name }}-
            ${{ runner.os }}-go-
            ${{ runner.os }}-
      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: "go.mod"
      - name: Run tests
        run: |
          go generate ./...
          go test ./... -v
